version: '3.8'

services:
  receipt-processor:
    build: .  # Build from Dockerfile instead of using pre-built image
    container_name: receipt-processor
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data  # SQLite database persistence
    env_file:
      - .env  # Load environment variables from .env file
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 